#include<iostream>
using namespace std;

void accept_record( int &number ){
  cout << "Number	:	";
  cin >> number;
}
int calculate( int num1, int num2 ){
  if( num2 == 0 )
	throw ArithmeticException("Divide by zero exception", __LINE__, __FUNCTION__, __FILE__ );
  return num1 / num2;
}
void print_record( int &result ){
  cout << "Result	:	" << result << endl;
}
int main( void ){
  try{
	int num1;
	accept_record( num1 );

	int num2;
	accept_record( num2 );

	int result = calculate( num1, num2 );
	print_record( result );

  }catch( ArithmeticException &ex ){
	  cout << ex.getMessage( ) <<endl;
  }
  return 0;
}
